server.port=8080

spring.datasource.url=jdbc:sqlite:pomodoro.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.servlet.session.timeout=1440m
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=false